### ISSUE TITLE
Add section on reaction mixture to PCR template

### ISSUE THREAD

**Issue by lukenoaa** [BeBOP-OBON/0_protocol_collection_template#12]
At present there is no place to say what should go into the PCR reaction (reagents, volumes, initial and final concentrations) except the primers. This could go in this section: https://github.com/BeBOP-OBON/0_protocol_collection_template/blob/main/protocol_template_PCR.md#pcr

**Comment by kpitz** [comment]
Added it in! Great suggestion.
