### ISSUE TITLE
Make this repository a "template repository"

### ISSUE THREAD

**Issue by MathewBiddle** [BeBOP-OBON/0_protocol_collection_template#13]
To make it easier for folks to fork and start working with this template, it might be beneficial to offer it as a template repository?

## Creating a template repository
You can make an existing repository a template, so you and others can generate new repositories with the same directory structure, branches, and files.
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

To see an example of this implemented in a repository, check out https://github.com/ioos/ioos-documentation-jekyll-skeleton
![image](https://github.com/BeBOP-OBON/0_protocol_collection_template/assets/8480023/cb1fe519-640d-4e63-89c5-8b72b5c21f63)

**Comment by kpitz** [comment]
Thanks for this suggestion! I didn't know about this option - I went ahead and made it a template repository.
