### ISSUE TITLE
Make meaning of MIOP terms more clear in the protocol templates

### ISSUE THREAD

**Issue by raissameyer** [BeBOP-OBON/0_protocol_collection_template#15]
Multiple people tested the protocol and the overall feedback was that the MIOP table was not clear. Include better guidance in the template and/or link to clear guidance.

**Comment by kpitz** [comment]
Added table with example values and definitions here for reference: https://github.com/BeBOP-OBON/0_protocol_collection_template/blob/main/MIOP_definition.md
